invx1:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: xo40924.ap-south-1.aws
      # User/password auth
      user: mahesh1998
      password: Mahesh1998@

      role: ACCOUNTADMIN
      database: INVX_DATABASE
      warehouse: INVX_WAREHOUSE
      schema: CLEANED_DATA
      threads: 10
      client_session_keep_alive: False
      # query_tag: [anything]

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)