
{{ config(materialized='table') }}

WITH source_data AS (
  SELECT
    "MAKE" AS BRAND,
    UPPER("VEHICLE RC"):: VARCHAR(255) AS REGISTRATION_NUMBER,
    "MODEL":: VARCHAR(255)  AS MODEL,
    "KEY COUNT":: VARCHAR(255)  AS VEHICLE_KEYS_AVAILABLE_COUNT,
    "CHASIS NO" :: VARCHAR(255) AS VEHICLE_CHASIS_NUMBER,
    "ENGINE NO" :: VARCHAR(255) AS VEHICLE_ENGINE_NUMBER,
    "RETAIL / WHOLESALE":: VARCHAR(255)  AS VEHICLE_TO_RETAIL_OR_WHOLESALE,
    "RC AVAILABILITY AT SOURCE" :: VARCHAR(255) AS RC_AVAILABILITY_AT_SOURCE,
    "DTC NAME" :: VARCHAR(255) AS DTC_CENTER_NAME,
    "DTC IN DATE(DD/MM/YY)" :: VARCHAR(255) AS DTC_VEHICLE_ARRIVED_DATE,
    "YEAR" :: VARCHAR(255) AS VEHICLE_MANUFACTURED_YEAR,
    "L2 DATE (DD/MM/YY)":: VARCHAR(255)  AS L2_INSPECTION_DATE,
    "ESTIMATION DATE" :: VARCHAR(255) AS ESTIMATED_REFURB_DATE,
    "APPROVAL DATE":: VARCHAR(255)  AS ESTIMATION_APPROVAL_DATE,
    "BAY ALLOCATION":: VARCHAR(255)  AS BAY_ALLOCATION_DATE,
    "PRODUCTION DATE" :: VARCHAR(255) AS REFURB_COMPLETED_DATE,
    "DTC OUT DATE" :: VARCHAR(255) AS DTC_OUT_DATE,
    "ESTIMATED SPARES COUNT" :: VARCHAR(255) AS ESTIMATED_SPARES_COUNT,
    "ESTIMATION AMOUNT" :: VARCHAR(255) AS ESTIMATED_REFURB_COST,
    "WORK END" :: VARCHAR(255) AS WORK_END_DATE,
    "TECHNICIAN NAME (END WORK)" :: VARCHAR(255) AS TECHNICIAN_NAME,
    "LUBRICATIONS :" :: VARCHAR(255) AS LUBRICATIONS_COST,
    "BATTERY :":: VARCHAR(255)  AS BATTERY_COST,
    "TIRE :" :: VARCHAR(255) AS TIRE_COST,
    "SPARES:" :: VARCHAR(255) AS SPARES_COST,
    "PAINT, TINKER, & OTHERS :" :: VARCHAR(255) AS PAINT_TINKER_OTHERS_COST,
    "OUTSIDE WORK :" :: VARCHAR(255) AS OUTSIDE_WORK_COST,
    "TOTAL RF COST:" :: VARCHAR(255) AS TOTAL_REFURB_COST,
    "STATUS" :: VARCHAR(255) AS REFURBISHMENT_STATUS,
    "REMARKS":: VARCHAR(1000)  AS REFURB_REMARKS
  FROM RAW_DATA.DTC

)

SELECT *
FROM source_data

/*
    Uncomment the line below to remove records with null `id` values
*/

-- where id is not null
